# Docs: https://jhugman.github.io/uniffi-bindgen-react-native/reference/config-yaml.html

rust:
  repo: https://github.com/hachimi-cat/moonlight-common-rust.git
  branch: 3b4b4d10359e437f63b39824e897c2dbfa9f1ddc
  manifestPath: bindings/Cargo.toml

web:
  entrypoint: web/uniffi/entry.ts
  tsBindings: web/uniffi
  defaultFeatures: false
  features: ["web"]
  manifestPatchFile: ./Cargo.wasm.toml
